export interface IStock {
    [index:string]:any;
    wine? : number;
    steak? : number;
    coffee? : number;
    salad? : number;
    egg_scramble? : number;
    bacon? : number;
    bread? : number;
    bread_baguette? : number;
    champagne? : number;
    cheese? : number;
    heart_little? : number;
    cupid? : number;
    plate_normal? : number;
    plate_box? : number;
    napkin_normal? : number;
    napkin_white_cotton? : number;
    napkin_linen? : number;
    plate_ceramic? : number;
    glass_plastic? : number;
    glass_ceramic? : number;
    tray_wood? : number;
    vase_flower? : number;
    tray_silver? : number;
    tray_plastic? : number;
};
